name: nodejs
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup yarn-cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache yarn global cache
        if: runner.os != 'macos-latest'
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn commitlint-circle
      - run: yarn lint
      - run: yarn build
      - run: yarn depcheck
      - name: upload cjs folder
        uses: actions/upload-artifact@v1
        with:
          name: cjs
          path: cjs
      - name: upload esm folder
        uses: actions/upload-artifact@v1
        with:
          name: esm
          path: esm
  test:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node-version: [10, 12, 14, 15]
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: setup yarn-cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: cache yarn global cache
        if: runner.os != 'macos-latest'
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn coverage --maxWorkers=2
      - name: codecov
        if: matrix.node-version == 14 && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v1
      - name: codacy
        if: matrix.node-version == 14 && matrix.os == 'ubuntu-latest' && github.repository == 'unional/path-equal'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
  release:
    name: release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v1
      - name: setup yarn-cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: cache yarn global cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: download cjs folder
        uses: actions/download-artifact@v1
        with:
          name: cjs
      - name: download esm folder
        uses: actions/download-artifact@v1
        with:
          name: esm
      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
