name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: unional/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'

  release:
    uses: unional/.github/.github/workflows/pnpm-release-changesets.yml@main
    needs: code
    secrets: inherit

  docgen:
      uses: unional/.github/.github/workflows/pnpm-docs.yml@main
      needs: release
