name: release
on:
  push:
    branches: [main]

jobs:
  code:
    uses: justland/.github/.github/workflows/yarn2-library-verify-linux.yml@main

  release:
    uses: justland/.github/.github/workflows/yarn2-library-release.yml@main
    needs: code
    secrets: inherit
